'use client';
import {useEffect,useState,useRef, type RefObject} from 'react';
import {ShaderGradient,ShaderGradientCanvas} from '@shadergradient/react';
export default function Atmosphere({analyser,playing}:{analyser:RefObject<AnalyserNode|null>,playing:boolean}){
const [supported,setSupported]=useState(false);const [active,setActive]=useState(true);const [bass,setBass]=useState(0);const [motion,setMotion]=useState(0);const root=useRef<HTMLDivElement>(null);
useEffect(()=>{const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;const c=document.createElement('canvas');const gl=c.getContext('webgl2');setSupported(!!gl&&!reduced&&innerWidth>700);gl?.getExtension('WEBGL_lose_context')?.loseContext();let lastY=scrollY,energy=0;const move=(e:PointerEvent)=>{if(reduced||e.pointerType!=='mouse')return;root.current?.style.setProperty('--mx',`${(e.clientX/innerWidth-.5)*35}px`);root.current?.style.setProperty('--my',`${(e.clientY/innerHeight-.5)*35}px`);energy=.4};const scroll=()=>{energy=Math.min(1,Math.abs(scrollY-lastY)/100);lastY=scrollY};const visibility=()=>setActive(!document.hidden);const timer=setInterval(()=>{energy*=.65;if(!document.hidden)setMotion(reduced?0:energy)},150);addEventListener('pointermove',move,{passive:true});addEventListener('scroll',scroll,{passive:true});document.addEventListener('visibilitychange',visibility);return()=>{clearInterval(timer);removeEventListener('pointermove',move);removeEventListener('scroll',scroll);document.removeEventListener('visibilitychange',visibility)}},[]);
useEffect(()=>{if(!playing||!active){setBass(0);return}const data=new Uint8Array(512);const timer=setInterval(()=>{const a=analyser.current;if(!a)return;a.getByteFrequencyData(data);let n=0;for(let i=1;i<5;i++)n+=data[i];setBass(Math.round(n/4/255*100)/100)},100);return()=>clearInterval(timer)},[playing,active,analyser]);
return <div ref={root} className="atmosphere" aria-hidden="true" data-bass={playing?bass:0} data-playing={playing} style={{'--intensity':.25+(playing?bass*.22:0)} as React.CSSProperties}><div className="fallback"/>{supported&&active&&<div className="shader" style={{transform:`scale(${1+bass*.06})`,opacity:.55+bass*.2}}><ShaderGradientCanvas pixelDensity={1} style={{width:'100%',height:'100%'}}><ShaderGradient type="plane" animate="on" uSpeed={.06+motion*.12+bass*.07} uStrength={1.5+bass} uDensity={1.4} uFrequency={4} color1="#000000" color2="#00F0FF" color3="#FF00A0" brightness={.8} grain="off" cDistance={3.6} cPolarAngle={90} cAzimuthAngle={0}/></ShaderGradientCanvas></div>}</div>
}
